/*
 * This source file was generated by the Gradle 'init' task
 */
package com.assignment;

public class App {
    // Locates the largest element in a 2D double array
    public static int[] locateLargest(double[][] arrayParam) {
        if (arrayParam == null || arrayParam.length == 0 || arrayParam[0].length == 0) {
            return new int[]{-1, -1};
        }
        
        int maxRow = 0;
        int maxCol = 0;
        double maxValue = arrayParam[0][0];

        for (int r = 0; r < arrayParam.length; r++) {
            for (int c = 0; c < arrayParam[r].length; c++) {
                if (arrayParam[r][c] > maxValue) {
                    maxValue = arrayParam[r][c];
                    maxRow = r;
                    maxCol = c;
                }
            }
        }
        return new int[]{maxRow, maxCol};
    }

    // Locates the largest element in a 2D int array
    public static int[] locateLargest(int[][] arrayParam) {
        if (arrayParam == null || arrayParam.length == 0 || arrayParam[0].length == 0) {
            return new int[]{-1, -1};
        }
        
        int maxRow = 0;
        int maxCol = 0;
        int maxValue = arrayParam[0][0];

        for (int r = 0; r < arrayParam.length; r++) {
            for (int c = 0; c < arrayParam[r].length; c++) {
                if (arrayParam[r][c] > maxValue) {
                    maxValue = arrayParam[r][c];
                    maxRow = r;
                    maxCol = c;
                }
            }
        }
        return new int[]{maxRow, maxCol};
    }

    // Locates the smallest element in a 2D double array
    public static int[] locateSmallest(double[][] arrayParam) {
        if (arrayParam == null || arrayParam.length == 0 || arrayParam[0].length == 0) {
            return new int[]{-1, -1};
        }
        
        int minRow = 0;
        int minCol = 0;
        double minValue = arrayParam[0][0];

        for (int r = 0; r < arrayParam.length; r++) {
            for (int c = 0; c < arrayParam[r].length; c++) {
                if (arrayParam[r][c] < minValue) {
                    minValue = arrayParam[r][c];
                    minRow = r;
                    minCol = c;
                }
            }
        }
        return new int[]{minRow, minCol};
    }

    // Locates the smallest element in a 2D int array
    public static int[] locateSmallest(int[][] arrayParam) {
        if (arrayParam == null || arrayParam.length == 0 || arrayParam[0].length == 0) {
            return new int[]{-1, -1};
        }
        
        int minRow = 0;
        int minCol = 0;
        int minValue = arrayParam[0][0];

        for (int r = 0; r < arrayParam.length; r++) {
            for (int c = 0; c < arrayParam[r].length; c++) {
                if (arrayParam[r][c] < minValue) {
                    minValue = arrayParam[r][c];
                    minRow = r;
                    minCol = c;
                }
            }
        }
        return new int[]{minRow, minCol};
    }
    
    //Print Values of an Array
    public static void printIntValues(int[][] arrayIntValues){
        for(int i = 0; i < arrayIntValues.length; ++i){

        for(int j = 0; j < arrayIntValues[i].length; ++j){

            System.out.print("[" + i + "][" + j + "] = " + arrayIntValues[i][j] + " ");
          }

          System.out.println();
        }
    }
    
    //Print Values of an Array
    public static void printDoubleValues(double[][] arrayDoubleValues){
        for(int i = 0; i < arrayDoubleValues.length; ++i){

        for(int j = 0; j < arrayDoubleValues[i].length; ++j){

            System.out.print("[" + i + "][" + j + "] = " + arrayDoubleValues[i][j] + " ");
          }

          System.out.println();
        }
    }

    // Simple test execution
    public static void main(String[] args) {
        double[][] doubleTestMatrix = {
            {1.5, 4.8, 9.2},
            {0.3, 12.7, 3.4},
            {6.1, -2.5, 8.8}
        };

        int[][] intTestMatrix = {
            {45, 12, 89, 23},
            {-10, 67, 4, 102},
            {31, 78, -50, 16}
        };

        int[] largestDoubleLoc = locateLargest(doubleTestMatrix);
        int[] smallestDoubleLoc = locateSmallest(doubleTestMatrix);
        
        int[] largestIntLoc = locateLargest(intTestMatrix);
        int[] smallestIntLoc = locateSmallest(intTestMatrix);
        
        

        System.out.println("Double Grid Results:");
        printDoubleValues(doubleTestMatrix);
        System.out.println("Largest element location: Row " + largestDoubleLoc[0] + ", Column " + largestDoubleLoc[1] + " Value = " + doubleTestMatrix[largestDoubleLoc[0]][largestDoubleLoc[1]]);
        System.out.println("Smallest element location: Row " + smallestDoubleLoc[0] +  ", Column " + smallestDoubleLoc[1] + " Value = " + doubleTestMatrix[smallestDoubleLoc[0]][smallestDoubleLoc[1]]);

        System.out.println("\nInteger Grid Results:");
        printIntValues(intTestMatrix);
        System.out.println("Largest element location: Row " + largestIntLoc[0] + ", Column " + largestIntLoc[1] + " Value = " + intTestMatrix[largestIntLoc[0]][largestIntLoc[1]]);
        System.out.println("Smallest element location: Row " + smallestIntLoc[0] + ", Column " + smallestIntLoc[1] + " Value = " + intTestMatrix[smallestIntLoc[0]][smallestIntLoc[1]]);
    }
}
