/*
 * This source file was generated by the Gradle 'init' task
 */
package com.assignment;
        
import java.util.Random;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner scanner = new Scanner(System.in);
        Random random = new Random();

        // Generate computer selection (1, 2, or 3)
        int computerInt = random.nextInt(3) + 1;

        // Prompt user for input
        System.out.println("Let us play Rock, Paper, Scissors!");
        System.out.println("Please enter your choice:");
        System.out.println("1 for Rock");
        System.out.println("2 for Paper");
        System.out.println("3 for Scissors");
        System.out.print("Your selection: ");

        int userInt = 0;
        if (scanner.hasNextInt()) {
            userInt = scanner.nextInt();
        } else {
            System.out.println("Invalid input. Please restart the program and enter a number.");
            scanner.close();
            return;
        }

        // Validate user input
        if (userInt < 1 || userInt > 3) {
            System.out.println("Invalid selection. You must enter 1, 2, or 3. Please restart the game.");
            scanner.close();
            return;
        }

        // Convert integer choices to readable strings
        String computerChoice = getChoiceName(computerInt);
        String userChoice = getChoiceName(userInt);

        // Display the results clearly
        System.out.println();
        System.out.println("----------------------------------------");
        System.out.println("GAME RESULTS");
        System.out.println("----------------------------------------");
        System.out.println("Computer selected: " + computerChoice + " (" + computerInt + ")");
        System.out.println("User selected:     " + userChoice + " (" + userInt + ")");
        System.out.println();

        // Determine the winner
        if (userInt == computerInt) {
            System.out.println("It is a draw!");
        } else if ((userInt == 1 && computerInt == 3) || 
                   (userInt == 2 && computerInt == 1) || 
                   (userInt == 3 && computerInt == 2)) {
            System.out.println("Congratulations, you win!");
        } else {
            System.out.println("Computer wins! Better luck next time.");
        }
        System.out.println("----------------------------------------");

        scanner.close();
    }

    // Helper method to translate numbers into game moves
    public static String getChoiceName(int choice) {
        switch (choice) {
            case 1:
                return "Rock";
            case 2:
                return "Paper";
            case 3:
                return "Scissors";
            default:
                return "Unknown";
        }
    }
}
