/*
 * This source file was generated by the Gradle 'init' task
 */
package com.assignment;

public class App {
    // 1. Overloaded method for short arrays
    public static short average(short[] array) {
        if (array.length == 0) return 0;
        long sum = 0; // Use a larger data type to prevent overflow during addition
        for (short num : array) {
            sum += num;
        }
        return (short) (sum / array.length);
    }

    // 2. Overloaded method for int arrays
    public static int average(int[] array) {
        if (array.length == 0) return 0;
        long sum = 0; // Use a larger data type to prevent overflow during addition
        for (int num : array) {
            sum += num;
        }
        return (int) (sum / array.length);
    }

    // 3. Overloaded method for long arrays
    public static long average(long[] array) {
        if (array.length == 0) return 0L;
        long sum = 0; 
        for (long num : array) {
            sum += num;
        }
        return sum / array.length;
    }

    // 4. Overloaded method for double arrays
    public static double average(double[] array) {
        if (array.length == 0) return 0.0;
        double sum = 0.0;
        for (double num : array) {
            sum += num;
        }
        return sum / array.length;
    }

    // Test program to invoke and verify each method
    public static void main(String[] args) {
        
        // Define arrays of completely different sizes
        short[] shortArray   = {10, 20, 30, 40};                     // Size 4
        int[] intArray       = {100, 250, 400, 550, 700};            // Size 5
        long[] longArray     = {1000L, 2000L, 3000L};                // Size 3
        double[] doubleArray = {1.5, 2.75, 4.0, 5.25, 6.5, 7.75};    // Size 6

        System.out.println("==================================================");
        System.out.println("        OVERLOADED ARRAY AVERAGE RESULTS          ");
        System.out.println("==================================================");

        // Test SHORT implementation
        printArray("Short Array", shortArray);
        System.out.println("Calculated Average (short): " + average(shortArray));
        System.out.println("--------------------------------------------------");

        // Test INT implementation
        printArray("Integer Array", intArray);
        System.out.println("Calculated Average (int): " + average(intArray));
        System.out.println("--------------------------------------------------");

        // Test LONG implementation
        printArray("Long Array", longArray);
        System.out.println("Calculated Average (long): " + average(longArray));
        System.out.println("--------------------------------------------------");

        // Test DOUBLE implementation
        printArray("Double Array", doubleArray);
        System.out.println("Calculated Average (double): " + average(doubleArray));
        System.out.println("==================================================");
    }

    // Helper method to display short array contents cleanly
    private static void printArray(String label, short[] array) {
        System.out.print(label + " [Size " + array.length + "]: ");
        for (int i = 0; i < array.length; i++) {
            System.out.print(array[i] + (i < array.length - 1 ? ", " : ""));
        }
        System.out.println();
    }

    // Helper method to display int array contents cleanly
    private static void printArray(String label, int[] array) {
        System.out.print(label + " [Size " + array.length + "]: ");
        for (int i = 0; i < array.length; i++) {
            System.out.print(array[i] + (i < array.length - 1 ? ", " : ""));
        }
        System.out.println();
    }

    // Helper method to display long array contents cleanly
    private static void printArray(String label, long[] array) {
        System.out.print(label + " [Size " + array.length + "]: ");
        for (int i = 0; i < array.length; i++) {
            System.out.print(array[i] + (i < array.length - 1 ? ", " : ""));
        }
        System.out.println();
    }

    // Helper method to display double array contents cleanly
    private static void printArray(String label, double[] array) {
        System.out.print(label + " [Size " + array.length + "]: ");
        for (int i = 0; i < array.length; i++) {
            System.out.print(array[i] + (i < array.length - 1 ? ", " : ""));
        }
        System.out.println();
    }
}
